apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: environment
spec:
  group: environment.eda.nokia.com
  version: v1alpha1
  title: Environment
  description: |
    This application provides workflows for environment configuration.

    It deploys CLI plugins and environment files to targets.
  image: ghcr.io/nokia-eda/apps/environment:v5.0.1
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  author: Nokia
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v4.0"
  appInfo:
    documentation: environment/docs
    categories:
      - "core"
    ociSpecVersion: v1.0.0
  components:
    - cr:
        path: environment/workflows/cliplugin/core_v1_flowdefinition.yaml
    - cr:
        path: environment/workflows/env/core_v1_flowdefinition.yaml
    - crd:
        api:
          expose: readWrite
        namespaced: true
        path: environment/crds/environment.eda.nokia.com_setupenvs.yaml
        schema: environment/openapiv3/eda_oas_environment.eda.nokia.com_setupenvs.json
        workflow: true
        ui:
          name: Push Environment
        names:
          plural: setupenvs
          singular: setupenv
          kind: SetupEnv
          listKind: SetupEnvList
    - crd:
        api:
          expose: readWrite
        namespaced: true
        path: environment/crds/environment.eda.nokia.com_cliplugins.yaml
        schema: environment/openapiv3/eda_oas_environment.eda.nokia.com_cliplugins.json
        workflow: true
        ui:
          name: Push CLI Plugin
        names:
          singular: cliplugin
          kind: CliPlugin
          listKind: CliPluginList
          plural: cliplugins
  dependencies:
    - file:
        path: environment/api/v1alpha1/pysrc
