apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: aaa-nokia-delete
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: delete
    apps:
      - app: aaa
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v4.0.0
          type: semver
