apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: coreext-nokia-install
  namespace: eda-system
spec:
  operation: install
  apps:
    - appId: coreext.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: semver
        value: v6.0.0
