apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: fabrics-nokia-delete
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: delete
    app: fabrics
    catalog: eda-catalog-builtin-apps
    vendor: nokia
    version:
      value: v2.0.0+24.12.1
      type: semver
