apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: interfaces-nokia-install
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: install
    apps:
      - app: interfaces
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v4.0.0
          type: semver
