apiVersion: appstore.eda.nokia.com/v1
kind: AppInstaller
metadata:
  name: mpls-nokia-delete
  namespace: eda-system
spec:
  operation: delete
  apps:
    - appId: mpls.eda.nokia.com
      catalog: eda-catalog-builtin-apps
      version:
        type: semver
        value: v6.0.0
