apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: protocols-nokia-delete
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: delete
    apps:
      - app: protocols
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v3.0.2+25.4.3
          type: semver
