apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: services-nokia-delete
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: delete
    apps:
      - app: services
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v4.0.2
          type: semver
