apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: services-nokia-install
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: install
    apps:
      - app: services
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v3.0.2+25.4.3
          type: semver
