apiVersion: core.eda.nokia.com/v1
kind: Workflow
metadata:
  name: siteinfo-nokia-delete
  namespace: eda-system
spec:
  type: app-installer
  input:
    operation: delete
    apps:
      - app: siteinfo
        catalog: eda-catalog-builtin-apps
        vendor: nokia
        version:
          value: v3.0.0+25.4.1
          type: semver
