apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: operatingsystem
spec:
  appInfo:
    categories:
      - system
    documentation: operatingsystem/docs
    ociSpecVersion: v1.0.0
  author: Nokia
  components:
    - cr:
        path: operatingsystem/workflows/image/core_v1_flowdefinition.yaml
    - crd:
        api:
          expose: readWrite
        namespaced: true
        path: operatingsystem/crds/os.eda.nokia.com_deployimages.yaml
        schema: operatingsystem/openapiv3/eda_oas_os.eda.nokia.com_deployimages.json
        workflow: true
        ui:
          name: Image
        names:
          plural: deployimages
          singular: deployimage
          kind: DeployImage
          listKind: DeployImageList
  dependencies:
    - file:
        path: operatingsystem/api/v1alpha1/pysrc/
    - file:
        path: operatingsystem/api/v1alpha1/pysrc
  description: |
    This application provides workflows managing the operating system version of targets.
  gitPathPrefix: /
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  group: os.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/operatingsystem:v5.0.2
  supportedCoreVersions:
    - "v4.0"
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  title: Operating System
  version: v1alpha1
