apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: aifabrics
spec:
  group: aifabrics.eda.nokia.com
  version: v1alpha1
  title: AIFabrics
  description: |
    This application provides automation resources relating to datacenter AI fabrics.
  image: ghcr.io/nokia-eda/apps/aifabrics:v5.0.0
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  gitPathPrefix: /
  author: Nokia
  appInfo:
    categories:
      - "networking"
    documentation: aifabrics/docs
    ociSpecVersion: v1.0.0
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v4.0"
  components:
    - crd:
        path: aifabrics/crds/aifabrics.eda.nokia.com_backends.yaml
        schema: aifabrics/openapiv3/eda_oas_aifabrics.eda.nokia.com_backends.json
        ui:
          category: AIFabrics
          name: Backends
        api:
          expose: readWrite
        names:
          plural: backends
          singular: backend
          kind: Backend
          listKind: BackendList
    - crd:
        path: aifabrics/crds/aifabrics.eda.nokia.com_backendstates.yaml
        schema: aifabrics/openapiv3/eda_oas_aifabrics.eda.nokia.com_backendstates.json
        api:
          expose: none
        names:
          plural: backendstates
          singular: backendstate
          kind: BackendState
          listKind: BackendStateList
    - script:
        path: aifabrics/intents/backend/backend_intent.py
        type: config
        trigger:
          kind: Backend
    - script:
        path: aifabrics/intents/backendstate/backendstate_intent.py
        type: state
        trigger:
          kind: BackendState
    - view:
        path: aifabrics/ui/aifabric-dashboard-v0.2.json
        ui:
          category: AIFabrics
          name: Backends
  dependencies:
    - file:
        path: aifabrics/intents
    - file:
        path: aifabrics/api/v1alpha1/pysrc
    - file:
        path: aifabrics
    - file:
        path: fabrics
    - file:
        path: common/
    - file:
        path: utils/
    - file:
        path: protocols/
    - file:
        path: qos/
    - file:
        path: services/
    - file:
        path: routingpolicies/
    - file:
        path: interfaces/
  requirements:
    - appId: fabrics.eda.nokia.com
      version: v5.0.0
    - appId: protocols.eda.nokia.com
      version: v5.0.0
    - appId: qos.eda.nokia.com
      version: v5.0.0
    - appId: services.eda.nokia.com
      version: v5.0.0
    - appId: routingpolicies.eda.nokia.com
      version: v5.0.0
    - appId: interfaces.eda.nokia.com
      version: v5.0.0
