apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: gitlab
spec:
  group: gitlab.eda.nokia.com
  version: v1alpha1
  title: Gitlab
  description: Creates Gitlab pipelines and issues.
  image: ghcr.io/nokia-eda/apps/gitlab:v1.0.0
  author: Nokia
  gitPathPrefix: /
  supportedCoreVersions:
    - "v4.0"
  appInfo:
    readme: README.md
    documentation: DOCUMENTATION.md
    license: LICENSE
    screenshots:
      - gl/assets/gitlab-logo.png
    categories:
      - "integrations"
    ociSpecVersion: v1.0.0
  components:
    - crd:
        path: gl/config/crd/bases/gitlab.eda.nokia.com_gitlabinstances.yaml
        schema: gl/docs/openapiv3/eda_oas_gitlab.eda.nokia.com_gitlabinstances.json
        namespaced: true
        api:
          expose: readWrite
        ui:
          category: Gitlab
          name: Instance
        kubernetes:
          exportPolicy: all
          importPolicy: all
        names:
          plural: gitlabinstances
          singular: gitlabinstance
          kind: GitlabInstance
          listKind: GitlabInstanceList
    - crd:
        path: gl/config/crd/bases/gitlab.eda.nokia.com_gitlabpipelines.yaml
        schema: gl/docs/openapiv3/eda_oas_gitlab.eda.nokia.com_gitlabpipelines.json
        namespaced: true
        api:
          expose: readWrite
        ui:
          category: Gitlab
          name: Action
        kubernetes:
          exportPolicy: all
          importPolicy: all
        names:
          singular: gitlabpipeline
          kind: GitlabPipeline
          listKind: GitlabPipelineList
          plural: gitlabpipelines
    - crd:
        path: gl/config/crd/bases/gitlab.eda.nokia.com_gitlabissues.yaml
        schema: gl/docs/openapiv3/eda_oas_gitlab.eda.nokia.com_gitlabissues.json
        namespaced: true
        api:
          expose: readWrite
        ui:
          category: Gitlab
          name: Issue
        kubernetes:
          exportPolicy: all
          importPolicy: all
        names:
          singular: gitlabissue
          kind: GitlabIssue
          listKind: GitlabIssueList
          plural: gitlabissues
    - crd:
        path: gl/config/crd/bases/gitlab.eda.nokia.com_creategitlabissues.yaml
        schema: gl/docs/openapiv3/eda_oas_gitlab.eda.nokia.com_creategitlabissues.json
        namespaced: true
        workflow: true
        api:
          expose: readWrite
        ui:
          name: Create Gitlab Issue
        names:
          listKind: CreateGitlabIssueList
          plural: creategitlabissues
          singular: creategitlabissue
          kind: CreateGitlabIssue
    - crd:
        path: gl/config/crd/bases/gitlab.eda.nokia.com_rungitlabpipelines.yaml
        schema: gl/docs/openapiv3/eda_oas_gitlab.eda.nokia.com_rungitlabpipelines.json
        namespaced: true
        workflow: true
        api:
          expose: readWrite
        ui:
          name: Run Gitlab Pipeline
        names:
          singular: rungitlabpipeline
          kind: RunGitlabPipeline
          listKind: RunGitlabPipelineList
          plural: rungitlabpipelines
    - cr:
        path: gl/manifests/webhooks.yaml
    - cr:
        path: gl/manifests/deployment.yaml
    - cr:
        path: workflows/v1alpha1/CreateGitlabIssue/flowdefinition.yaml
    - cr:
        path: workflows/v1alpha1/RunGitlabPipeline/flowdefinition.yaml
  dependencies:
    - container:
        name: gitlab-controller
        image: ghcr.io/nokia-eda/apps/gitlab-controller:v1.0.0
