apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: nutanix
spec:
  appInfo:
    categories:
      - "integrations"
    documentation: nutanix/docs
    ociSpecVersion: v1.0.0
  author: nokia
  dependencies:
    - file:
        path: utils
    - file:
        path: common
    - file:
        path: nutanix/intents
    - file:
        path: nutanix/api
    - file:
        path: nutanix/deps
    - file:
        path: nutanix/alarms/pysrc
    - container:
        name: nutanix-plugin-container
        image: image/nutanix-plugin-container
  description: A plugin integrating Nutanix Prism Central with Cloud Connect
  group: nutanix.eda.nokia.com
  image: ghcr.io/nokia-eda/apps/nutanix-plugin:v6.0.0
  supportedCoreVersions:
    - "v5.0.0"
  requirements:
    - appId: connect.eda.nokia.com
      version: "v6.0.*"
  title: Connect Nutanix Prism Operator
  version: v2
  components:
    - crd:
        api:
          expose: readWrite
        path: nutanix/crds/nutanix.eda.nokia.com_nutanixplugininstances.yaml
        schema: nutanix/openapiv3/eda_oas_nutanix.eda.nokia.com_nutanixplugininstances.json
        namespaced: false
        ui:
          category: Connect
          name: Nutanix Plugins
          panel: system_administration
          icon: ConnectionInternal
        kubernetes:
          exportPolicy: all
          importPolicy: all
        conversionScript: nutanix/intents/nutanixplugininstance/conversion_v2.py
        names:
          plural: nutanixplugininstances
          singular: nutanixplugininstance
          kind: NutanixPluginInstance
          listKind: NutanixPluginInstanceList
    - cr:
        path: nutanix/alarms/alarms.yaml
    - script:
        path: nutanix/intents/nutanixplugininstance/config_intent.py
        trigger:
          kind: NutanixPluginInstance
        type: config
