apiVersion: core.eda.nokia.com/v1
kind: Manifest
metadata:
  name: security
spec:
  group: security.eda.nokia.com
  version: v1alpha1
  title: Security
  description: |
    This application provides resources related to security for various Network Operating Systems.
  image: ghcr.io/nokia-eda/apps/security:v5.0.2
  gitReference: 1da44402c90fbeba1161ccb8ea3350ef0353843d
  gitPathPrefix: /
  author: Nokia
  appInfo:
    documentation: security/docs
    categories:
      - "system"
    ociSpecVersion: v1.0.0
  supportedEndpoints:
    - "srl:24.10.*"
    - "srl:25.3.*"
    - "srl:25.7.*"
    - "srl:25.10.*"
    - "sros:24.10.r4+"
    - "sros:25.3.r2+"
    - "sros:25.7.*"
    - "sros:25.10.*"
    - "eos:4.33.2f:beta"
    - "nxos:10.5.2:alpha"
  supportedCoreVersions:
    - "v4.0"
  components:
    - crd:
        path: security/crds/security.eda.nokia.com_keychains.yaml
        schema: security/openapiv3/eda_oas_security.eda.nokia.com_keychains.json
        ui:
          category: Security
          name: Keychains
        api:
          expose: readWrite
        names:
          singular: keychain
          kind: Keychain
          listKind: KeychainList
          plural: keychains
    - crd:
        path: security/crds/security.eda.nokia.com_keychaindeployments.yaml
        schema: security/openapiv3/eda_oas_security.eda.nokia.com_keychaindeployments.json
        ui:
          category: Security
          name: Keychain Deployments
        api:
          expose: readWrite
        names:
          plural: keychaindeployments
          singular: keychaindeployment
          kind: KeychainDeployment
          listKind: KeychainDeploymentList
    - script:
        path: security/intents/keychain/keychain_intent.py
        type: config
        trigger:
          kind: Keychain
    - script:
        path: security/intents/keychaindeployment/keychaindeployment_intent.py
        type: config
        trigger:
          kind: KeychainDeployment
  dependencies:
    - file:
        path: security/intents
    - file:
        path: security/api/v1alpha1/pysrc
    - file:
        path: common/
    - file:
        path: utils/
    - file:
        path: interfaces/
  requirements:
    - appId: interfaces.eda.nokia.com
      version: v5.0.2
